# Catatan

In [ ]:
a<-c(3.2, 1.7, -11.3, -.67, 4, 0)
a[0]

#Mengambil nilai elemen vektor pada index tertentu
elemen3<-a[3]; elemen3


#Mengambil beberapa elemen dari suatu vektor, dan mengubah elemen vektor
a[1:3]; a[c(2,3,5)]
a[3] = a[3] -4;
a

#Menambah index vektor
a[7] <- 10
a[10]<- 20; a
a[1] <- 100 #menimpa elemen baru pada index yang ada
a

#Aritmatika vektor
a<- a-1; a
a<- a^2; a
b<- c(1,1,1,1)
b<- b+1:4;b

#Megenerasi sekuens
seq(1,10,2)
seq(1,3,.5)
seq(1,5, length.out=7)
seq(1,5, length.out=9)

#Merepetisi elemen vektor
rep(1.5, 5)
rep(4,20)
q<-c(3,7);q
rep(q, 5)


#Meregenerasi elemen random pada vektor
# Distribusi Uniform
distUniform<-runif(10,1,5); distUniform
summary(distUniform)


#Distribusi Normal
distNormal<-rnorm(10,5,1); distNormal
summary(distNormal)


#Menuliskan Data Frames
a<-c(1,2,3,4)
b<- c(2,4,6,8)
levels <- factor(c("A","B","A","B"))
df<-data.frame(first=a, second=b, f=levels)

df



#Menghitung Jumlah Data Baris atau Kolom
nrow(df)
ncol(df)


#Ekstrak data frames
df<- data.frame(c(183, 175,178),
                c(85,76,79),
                c(40,35,38))

names(df)<-c("Height", "Weight", "Age")

df


#Mengambil nama header kolom
names(df[1])
names(df[2])
names(df[3])



#Latihan Ekstrak Data Frames
#Temukan
# Baris pertama dan kolom2 dan 3?
#Baris 1 dan 2 dan kolom2 dan 3?
#Hanya kolom pertama dengan semua data baris?
#Kolom 1 dan 3 dengan semua data baris?

# First Row and 2nd and 3rd column
df[1, 2:3]
# First, Second Row and Second and Third Column
df[1:2, 2:3]
# Just First Column with All rows
df[, 1]
# First and Third Column with All rows
df[,c(1,3)]



#Representasi Matriks
#Mengambil nilai elemen dalam matriks

#Perkalian elemen matriks
(m1<-matrix(c(1,2,3,4,5,6,7,8,9), nrow=3, ncol=3))

(m2<-matrix(c(1,2,3,4,5,6,7,8,9), byrow=TRUE, ncol=3))




#Menggabungkan 2 vektor kolom ataupun vektor baris
v1<-1:4;v2<-5:8
v1;v2
rbind(v1,v2);cbind(v1,v2)

#Membuat matriks diagonal
diag(3)
diag(5)
diag(1:5)
diag(c(3,7,8,9,15))


#Operasi matriks lain
#Transpose
m1
t(m1)

#Determinan
A<-rbind(c(3,1), c(2,5))
A
det(A)

# Latihan

In [ ]:
# Wrong way to do it
df = data.frame(
  c("adit", "tpl", 2018, 3.15),
  c("bayu", "si", 2017, 3.00),
  c("chintya", "tpl", 2017, 3.53),
  c("david", "ti", 2019, 3.77),
  c("ervita", "ti", 2018, 3.42),
  c("fahmi", "ti", 2017, 3.33),
  c("gabriel", "tpl", 2016, 3.19),
  c("hendra", "si", 2018, 2.95),
  c("indri", "tpl", 2018, 3.25),
  c("jeffry", "tpl", 2019, 3.72)
                )

names(df)<-c("nama","prodi","angkatan","ipk")
df


# Correct way to do it
# Create the data frame
df <- data.frame(
  nama = c("adit", "bayu", "chintya", "david", "ervita", "fahmi", "gabriel", "hendra", "indri", "jeffry"),
  prodi = c("tpl", "si", "tpl", "ti", "ti", "ti", "tpl", "si", "tpl", "tpl"),
  angkatan = c(2018, 2017, 2017, 2019, 2018, 2017, 2016, 2018, 2018, 2019),
  ipk = c(3.15, 3.00, 3.53, 3.77, 3.42, 3.33, 3.19, 2.95, 3.25, 3.72)
)

# Show the data frame as a table
df

# I need to plan when to put it into csv, and either is it possible or not is still a mystery


# Other way to do it
# a<-c("adit", "bayu", "chintya", "david", "ervita", "fahmi", "gabriel")